//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scorpio.Outlook.AddIn.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(Scorpio.Outlook.AddIn.Misc.ScorpioSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0a074de714f3ddee51d64cd8c8a0722846bf535d")]
        public string RedmineApiKey {
            get {
                return ((string)(this["RedmineApiKey"]));
            }
            set {
                this["RedmineApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(Scorpio.Outlook.AddIn.Misc.ScorpioSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://services.orconomy.de/redmine")]
        public string RedmineURL {
            get {
                return ((string)(this["RedmineURL"]));
            }
            set {
                this["RedmineURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(Scorpio.Outlook.AddIn.Misc.ScorpioSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int RedmineHolidayIssue {
            get {
                return ((int)(this["RedmineHolidayIssue"]));
            }
            set {
                this["RedmineHolidayIssue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(Scorpio.Outlook.AddIn.Misc.ScorpioSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("82")]
        public int RedmineUseOvertimeIssue {
            get {
                return ((int)(this["RedmineUseOvertimeIssue"]));
            }
            set {
                this["RedmineUseOvertimeIssue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(Scorpio.Outlook.AddIn.Misc.ScorpioSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1900-01-01")]
        public global::System.DateTime LastIssueSyncDate {
            get {
                return ((global::System.DateTime)(this["LastIssueSyncDate"]));
            }
            set {
                this["LastIssueSyncDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(Scorpio.Outlook.AddIn.Misc.ScorpioSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastUsedIssues {
            get {
                return ((string)(this["LastUsedIssues"]));
            }
            set {
                this["LastUsedIssues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(Scorpio.Outlook.AddIn.Misc.ScorpioSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteIssues {
            get {
                return ((string)(this["FavoriteIssues"]));
            }
            set {
                this["FavoriteIssues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(Scorpio.Outlook.AddIn.Misc.ScorpioSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double RefreshTime {
            get {
                return ((double)(this["RefreshTime"]));
            }
            set {
                this["RefreshTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(Scorpio.Outlook.AddIn.Misc.ScorpioSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int LimitForIssueNumber {
            get {
                return ((int)(this["LimitForIssueNumber"]));
            }
            set {
                this["LimitForIssueNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(Scorpio.Outlook.AddIn.Misc.ScorpioSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int NumberLastUsedIssues {
            get {
                return ((int)(this["NumberLastUsedIssues"]));
            }
            set {
                this["NumberLastUsedIssues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(Scorpio.Outlook.AddIn.Misc.ScorpioSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WatchedProjects {
            get {
                return ((string)(this["WatchedProjects"]));
            }
            set {
                this["WatchedProjects"] = value;
            }
        }
    }
}
